version: '3'
services:
  polkadot:
    build:
      context: .
    ports:
      - "127.0.0.1:30333:30344/tcp"
      - "127.0.0.1:9933:9944/tcp"
    image: polkadot-alexander-sandbox:latest
    volumes:
      - ".:/alexander/polkadot"
    command: tail -f /dev/null
