version: '3'
services:
  polkadot:
    build:
      context: .
    ports:
      - "127.0.0.1:30333:30344/tcp"
      - "127.0.0.1:9933:9944/tcp"
    image: substrate-charred-cherry-sandbox:latest
    volumes:
      - ".:/charred-cherry/substrate/"
    command: tail -f /dev/null
